export const IMPORT_KINDS=['gmail_scan','expense_document','sales_document','transport_tariff','shopify_orders','sendcloud_orders','envia_shipments'] as const;
export type ImportKind=typeof IMPORT_KINDS[number];
export type JobStatus='queued'|'running'|'waiting_review'|'completed'|'completed_with_errors'|'failed'|'cancelled';
export type ItemStatus='queued'|'running'|'waiting_review'|'ready'|'imported'|'duplicate'|'skipped'|'error'|'cancelled';
export type ImportJob={id:string;owner_id:string;created_by:string;kind:ImportKind;module:string;account_id:string|null;label:string;status:JobStatus;stage:string;options:Record<string,unknown>;total:number;processed:number;imported:number;review:number;failed:number;skipped:number;created_at:string;updated_at:string;cancel_requested:boolean;request_key:string};
export type ImportItem={id:string;job_id:string;owner_id:string;item_key:string;label:string;status:ItemStatus;stage:string;source_document_id:string|null;input:Record<string,unknown>;result:Record<string,unknown>;checkpoint:Record<string,unknown>;attempts:number;max_attempts:number;retryable:boolean;error:string|null;lease_token:string|null;lease_until:string|null;version:number;created_at:string;updated_at:string};
export type ImportOutcome={status:'queued'|'waiting_review'|'imported'|'duplicate'|'skipped'|'error';stage?:string;result?:Record<string,unknown>;checkpoint?:Record<string,unknown>;error?:string;retryable?:boolean;delaySeconds?:number};
export const importModule=(kind:ImportKind)=>kind==='sales_document'?'sales':kind==='transport_tariff'?'settings':kind.endsWith('_orders')||kind==='envia_shipments'?'orders':'invoices';
export const importLabel:Record<ImportKind,string>={gmail_scan:'Actualizar Gmail',expense_document:'Importar gastos',sales_document:'Importar facturas de venta',transport_tariff:'Importar tarifa',shopify_orders:'Importar pedidos de Shopify',sendcloud_orders:'Importar pedidos de Sendcloud',envia_shipments:'Importar envíos de Envia.com'};
