import {useEffect,useState} from 'react';
import {InvoiceEngine} from '../services/invoiceEngine';
import {invoiceCandidateToInput} from '../services/invoiceImportPipeline';
import type {ExpenseCategory,InvoiceImportCandidate,InvoiceSource} from '../types';
import {InvoiceCandidateForm} from './InvoiceCandidateForm';
export function InvoiceEngineQueue({categories,onImported}:{categories:ExpenseCategory[];onImported:()=>Promise<void>|void}){
  const [jobs,setJobs]=useState<any[]>([]),[candidate,setCandidate]=useState<InvoiceImportCandidate|null>(null),[source,setSource]=useState<InvoiceSource>('manual'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[discard,setDiscard]=useState<string|null>(null);
  const load=async()=>{try{setJobs(await InvoiceEngine.pending())}catch{/* Migration may not yet exist on the production environment. */}};
  useEffect(()=>{void load();const listener=()=>void load();window.addEventListener('zenvia:invoice-engine-updated',listener);return()=>window.removeEventListener('zenvia:invoice-engine-updated',listener)},[]);
  const open=async(job:any)=>{setError('');setBusy(true);try{setCandidate(await InvoiceEngine.reopen(job));setSource(job.source_channel)}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir el original.')}finally{setBusy(false)}};
  const save=async()=>{if(!candidate)return;setBusy(true);setError('');try{await InvoiceEngine.save(invoiceCandidateToInput(candidate,source,true));setCandidate(null);await load();await onImported()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}};
  const split=async()=>{if(!candidate)return;setBusy(true);try{setCandidate(await InvoiceEngine.split(candidate,source));await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo separar.')}finally{setBusy(false)}};
  const ignore=async(id:string)=>{setBusy(true);try{await InvoiceEngine.ignore(id);setDiscard(null);await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo descartar.')}finally{setBusy(false)}};
  if(!jobs.length&&!candidate&&!error)return null;
  return <section className="invoiceEngineQueue"><strong>Revisión de importaciones · {jobs.length}</strong><p>Los originales quedan guardados. Corrige los campos dudosos; aprenderemos las correcciones para este proveedor.</p>{jobs.map(job=><div className="invoiceEngineQueueRow" key={job.id}><span>{job.document.supplier?.name||'Proveedor pendiente'} · {job.document.number||'Sin número'} · {job.source_channel}</span><button className="secondary" disabled={busy} onClick={()=>void open(job)}>Revisar</button>{discard===job.id?<><button className="secondary" disabled={busy} onClick={()=>void ignore(job.id)}>Confirmar descarte</button><button onClick={()=>setDiscard(null)}>Cancelar</button></>:<button className="secondary" disabled={busy} onClick={()=>setDiscard(job.id)}>Descartar</button>}</div>)}
  {candidate&&<div className="modalBackdrop"><div className="modal invoiceModal"><div className="modalHead"><h3>Revisar factura</h3><button disabled={busy} onClick={()=>setCandidate(null)}>Cerrar</button></div><InvoiceCandidateForm candidate={candidate} categories={categories} onChange={setCandidate}/>{error&&<div className="errorBox">{error}</div>}<div className="modalActions"><button className="secondary" disabled={busy} onClick={()=>void split()}>Separar otra factura del mismo original</button><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Guardando…':'Confirmar y guardar'}</button></div></div></div>}{error&&!candidate&&<div className="errorBox">{error}</div>}</section>;
}
