import {useEffect,useRef,useState} from 'react';
import {Camera,FileUp,History,LoaderCircle} from 'lucide-react';
import {useImportJobs} from '../context/ImportJobsContext';
import {prepareManualImportReview,actOnImport,loadImportJob,loadImportOriginal,reviewImportItem,startDocumentImport,type ImportItem,type ImportJob,type ImportKind} from '../services/importJobs';
import {importLabel} from '../../shared/imports/contracts';
import {FormModal} from './forms/FormPrimitives';
import {SearchableSelect} from './forms/SearchableSelect';
import {InvoiceCandidateForm} from './InvoiceCandidateForm';
import {ensureSalesSeries,loadClients,type Client,type SalesInvoiceSeries} from '../services/sales';
import type {ExpenseCategory,InvoiceImportCandidate} from '../types';
import {imageFilesToPdf} from '../services/pdf';
import {confirmAction} from '../services/actionDialog';
import './persistent-imports.css';
const labels:Record<string,string>={queued:'En cola',ready:'Lista',running:'En curso',waiting_review:'Revisar',completed:'Completada',completed_with_errors:'Completada con incidencias',failed:'Error',cancelled:'Cancelada',imported:'Importada',duplicate:'Duplicada',skipped:'Omitida',error:'Error'};
type Candidate=Record<string,any>;
function ReviewForm({kind,candidate,onChange,categories}:{kind:ImportKind;candidate:Candidate;onChange:(c:Candidate)=>void;categories:ExpenseCategory[]}){
 const [clients,setClients]=useState<Client[]>([]),[series,setSeries]=useState<SalesInvoiceSeries[]>([]),[error,setError]=useState('');
 useEffect(()=>{let alive=true;if(kind==='sales_document')Promise.all([loadClients(),ensureSalesSeries(Number(String(candidate.issueDate||'').slice(0,4))||new Date().getFullYear())]).then(([c,s])=>{if(alive){setClients(c);setSeries(s.filter(x=>x.active&&x.kind==='standard'));}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[kind,candidate.issueDate]);
 const field=(key:string,label:string,type='text')=><label key={key}>{label}<input type={type} step={type==='number'?'0.01':undefined} value={candidate[key]??''} onChange={e=>onChange({...candidate,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>;
 if(kind==='transport_tariff'){
  const services=Array.isArray(candidate.services)?candidate.services:[];
  const editService=(index:number,key:string,value:any)=>onChange({...candidate,services:services.map((service:Candidate,i:number)=>i===index?{...service,[key]:value}:service)});
  return <><div className="invoiceFormGrid">{field('carrierName','Transportista')}{field('carrierCode','Código de transportista')}{field('currencyCode','Divisa')}{field('effectiveFrom','Vigente desde','date')}{field('effectiveTo','Vigente hasta','date')}</div><h4>Servicios y tramos</h4>{services.map((service:Candidate,index:number)=><section className="formSection" key={index}><div className="invoiceFormGrid">{[['serviceName','Servicio'],['canonicalServiceKey','Código del servicio']].map(([key,label])=><label key={key}>{label}<input value={service[key]||''} onChange={e=>editService(index,key,e.target.value)}/></label>)}</div>{(service.bands||[]).map((band:Candidate,position:number)=><div className="importLine" key={position}>{[['countryCode','País'],['zoneCode','Código de zona'],['zoneName','Zona'],['minWeightKg','Desde kg'],['maxWeightKg','Hasta kg'],['basePrice','Precio base'],['extraKgPrice','Precio por kg extra']].map(([key,label],i)=><label key={key}>{label}<input type={i<3?'text':'number'} step="0.01" value={band[key]??''} onChange={e=>editService(index,'bands',service.bands.map((b:Candidate,n:number)=>n===position?{...b,[key]:i<3?e.target.value:e.target.value===''?null:Number(e.target.value)}:b))}/></label>)}</div>)}<button className="secondary" type="button" onClick={()=>editService(index,'bands',[...(service.bands||[]),{countryCode:'ES',zoneCode:'',zoneName:'',minWeightKg:0,maxWeightKg:null,basePrice:null,extraKgPrice:null}])}>Añadir tramo</button></section>)}<button className="secondary" type="button" onClick={()=>onChange({...candidate,services:[...services,{serviceName:'',canonicalServiceKey:'',bands:[]}]})}>Añadir servicio</button></>;
 }

 const sales=kind==='sales_document';
 const editLine=(index:number,key:string,value:any)=>{const lines=[...candidate.lines];lines[index]={...lines[index],[key]:value};const round=(n:number)=>Math.round(n*100)/100;const next:Candidate={...candidate,lines};if(sales){next.subtotal=round(lines.reduce((sum,l)=>sum+round(l.quantity*l.unitPrice*(1-(l.discountPercent||0)/100)),0));next.taxAmount=round(lines.reduce((sum,l)=>sum+round(round(l.quantity*l.unitPrice*(1-(l.discountPercent||0)/100))*l.taxRate/100),0));next.totalAmount=round(next.subtotal+next.taxAmount);}else{const l=lines[index],net=round(l.quantity*l.unitPrice);lines[index]={...l,lineNet:net,taxAmount:round(net*l.taxRate/100),lineTotal:round(net*(1+l.taxRate/100)),normalizedUnitPrice:l.unitPrice};}onChange(next);};
 return <>{error&&<p role="alert">{error}</p>}{sales?<div className="invoiceFormGrid">
  {field('invoiceNumber','Número de factura')}{field('issueDate','Fecha','date')}{field('dueDate','Vencimiento','date')}{field('currency','Divisa')}
  <label>Cliente<SearchableSelect value={candidate.clientId||''} onChange={value=>onChange({...candidate,clientId:value})} allowEmpty emptyLabel="Crear cliente propuesto" options={clients.map(c=>({value:c.id,label:c.name}))} ariaLabel="Cliente de la factura"/></label>
  {!candidate.clientId&&<><label>Nombre del cliente<input value={candidate.proposedClient?.name||''} onChange={e=>onChange({...candidate,proposedClient:{...candidate.proposedClient,name:e.target.value}})}/></label><label>NIF del cliente<input value={candidate.proposedClient?.taxId||''} onChange={e=>onChange({...candidate,proposedClient:{...candidate.proposedClient,taxId:e.target.value}})}/></label></>}
  <label>Serie<SearchableSelect value={candidate.seriesId||''} onChange={value=>onChange({...candidate,seriesId:value})} options={series.map(s=>({value:s.id,label:s.prefix+' · '+s.year}))} ariaLabel="Serie de la factura"/></label>
  {field('subtotal','Base imponible','number')}{field('taxAmount','IVA','number')}{field('totalAmount','Total','number')}
 </div>:<><InvoiceCandidateForm candidate={{supplierName:'',invoiceNumber:'',invoiceDate:'',subtotal:0,vat:0,total:0,withholding:0,equivalenceSurcharge:0,...candidate} as InvoiceImportCandidate} categories={categories} onChange={next=>{const copy={...next} as Candidate;if(next.supplierName!==candidate.supplierName)delete copy.supplierId;onChange(copy)}}/><div className="invoiceFormGrid">{field('supplierTaxId','NIF del proveedor')}{field('supplierEmail','Correo del proveedor')}{field('supplierAddress','Dirección del proveedor')}{field('recipientTaxId','NIF del destinatario')}</div></>}
 <label>Tipo de documento<SearchableSelect value={candidate.documentKind||'invoice'} onChange={value=>onChange({...candidate,documentKind:value})} options={[{value:'invoice',label:'Factura'},{value:'credit_note',label:'Abono'},{value:'not_invoice',label:'No es una factura'}]} ariaLabel="Tipo de documento original"/></label><h4>Líneas de factura</h4>{(candidate.lines||[]).map((line:Candidate,index:number)=><div className="importLine" key={index}>{[['description','Descripción'],['quantity','Cantidad'],['unitPrice','Precio unitario'],['taxRate','IVA (%)']].map(([key,label])=><label key={key}>{label}<input type={key==='description'?'text':'number'} step="0.01" value={line[key]??''} onChange={e=>{editLine(index,key,key==='description'?e.target.value:Number(e.target.value))}}/></label>)}<button type="button" onClick={()=>onChange({...candidate,lines:candidate.lines.filter((_:unknown,i:number)=>i!==index)})}>Quitar</button></div>)}
 <button type="button" className="secondary" onClick={()=>onChange({...candidate,lines:[...(candidate.lines||[]),{description:'',quantity:1,unitPrice:0,taxRate:21}]})}>Añadir línea</button></>;
}
export function ImportJobDetail({jobId,onClose,categories=[]}:{jobId:string;onClose:()=>void;categories?:ExpenseCategory[]}){
 const {refresh}=useImportJobs();const [detail,setDetail]=useState<{job:ImportJob;items:ImportItem[]}|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<ImportItem|null>(null),[candidate,setCandidate]=useState<Candidate>({}),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true,sequence=0;const fetchDetail=async()=>{const request=++sequence;try{const d=await loadImportJob(jobId);if(alive&&request===sequence){setDetail(d);setError('')}}catch(e){if(alive&&request===sequence)setError((e as Error).message)}};void fetchDetail();const timer=setInterval(fetchDetail,5000);return()=>{alive=false;clearInterval(timer)}},[jobId]);
 const run=async(action:'cancel'|'retry')=>{if(action==='cancel'&&!await confirmAction({title:'Cancelar importación',message:'Se detendrán los documentos pendientes. Los registros ya importados se conservan.',confirmLabel:'Cancelar importación',tone:'danger'}))return;setBusy(true);try{setDetail(await actOnImport(jobId,action));await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const manual=async(item:ImportItem)=>{setBusy(true);try{const d=await prepareManualImportReview(item);setDetail(d);const next=d.items.find(i=>i.id===item.id)!;setSelected(next);setCandidate(structuredClone(next.result.candidate||{}));await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const save=async()=>{if(!selected)return;setBusy(true);setError('');try{const next=await reviewImportItem(selected,candidate);setDetail(next);setSelected(null);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const original=async(item:ImportItem)=>{try{const source=await loadImportOriginal(item.source_document_id!);window.open(source.url,'_blank','noopener,noreferrer')}catch(e){setError((e as Error).message)}};
 return <FormModal title={detail?.job.label||'Importación'} subtitle="El proceso continúa aunque cierres esta ventana." onClose={onClose} actions={<><button className="secondary" onClick={onClose}>Cerrar</button>{detail?.items.some(i=>i.status==='error'&&i.retryable)&&<button disabled={busy} onClick={()=>void run('retry')}>Reintentar incidencias</button>}{detail&&['queued','running','waiting_review'].includes(detail.job.status)&&<button disabled={busy} className="danger" onClick={()=>void run('cancel')}>Cancelar importación</button>}{selected&&<button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Guardando…':'Confirmar datos e importar'}</button>}</>}>
 {error&&<p className="errorBox" role="alert">{error}</p>}{!detail&&<p>Cargando…</p>}{detail&&<><p>{labels[detail.job.status]} · {detail.job.stage}</p><p>{detail.job.imported} importados · {detail.job.review} por revisar · {detail.job.failed} incidencias · {detail.job.skipped} omitidos</p>
 <div className="importHistory">{detail.items.map(item=><div className="importHistoryRow" key={item.id}><div><strong>{item.label}</strong><span>{labels[item.status]} · {item.stage}</span>{item.error&&<span role="alert">{item.error}</span>}</div><div>{item.source_document_id&&<button className="secondary" onClick={()=>void original(item)}>Original</button>}{item.status==='error'&&['expense_document','sales_document'].includes(detail.job.kind)&&<button disabled={busy} onClick={()=>void manual(item)}>Completar manualmente</button>}{item.status==='waiting_review'&&<button onClick={()=>{setSelected(item);setCandidate(structuredClone(item.result.candidate||{}))}}>Revisar</button>}</div></div>)}</div>
 {selected&&<section className="formSection"><h4>{selected.label}</h4><p>{candidate.reviewReason}</p><ReviewForm kind={detail.job.kind} candidate={candidate} onChange={setCandidate} categories={categories}/></section>}</>}
 </FormModal>;
}
export function ImportJobHistory({kinds,categories=[]}:{kinds?:ImportKind[];categories?:ExpenseCategory[]}){
 const {jobs,amazon,error}=useImportJobs();const [selected,setSelected]=useState<string|null>(null);const visible=jobs.filter(j=>!kinds||kinds.includes(j.kind));
 return <><div className="importHistory">{error&&<p className="errorBox">{error}</p>}{!visible.length&&<p>No hay importaciones registradas.</p>}{visible.map(job=><button type="button" className="importHistoryRow" key={job.id} onClick={()=>setSelected(job.id)}><div><strong>{job.label}</strong><span>{new Date(job.created_at).toLocaleString('es-ES')} · {job.stage}</span></div><div><span>{labels[job.status]}</span><small>{job.processed}/{job.total} · {job.review} por revisar</small></div></button>)}</div>{!kinds&&amazon.length>0&&<><h4>Amazon</h4><div className="importHistory">{amazon.map(job=><div key={job.id} className="importHistoryRow"><div><strong>Amazon · {job.source}</strong><span>{new Date(job.created_at).toLocaleString('es-ES')}</span>{job.last_error&&<span>{job.last_error}</span>}</div><div><span>{job.status==='success'?'Completada':labels[job.status]||job.status}</span><small>{job.rows_processed} registros</small></div></div>)}</div></>}{selected&&<ImportJobDetail key={selected} jobId={selected} categories={categories} onClose={()=>setSelected(null)}/>}</>;
}
export function ImportJobCenter({categories}:{categories:ExpenseCategory[]}){const {jobs,amazon}=useImportJobs();const [open,setOpen]=useState(false);const active=jobs.filter(j=>['queued','running','waiting_review'].includes(j.status)).length+amazon.filter(j=>['queued','running'].includes(j.status)).length;return <><button className="secondary" title="Importaciones" onClick={()=>setOpen(true)}><History size={18}/>{active>0&&<span>{active}</span>}</button>{open&&<FormModal title="Importaciones" subtitle="Progreso, revisiones e historial de todas las secciones." onClose={()=>setOpen(false)}><ImportJobHistory categories={categories}/></FormModal>}</>}
export function PersistentDocumentImportModal({open,onClose,kind,categories=[],multiple=true}:{open:boolean;onClose:()=>void;kind:'expense_document'|'sales_document';categories?:ExpenseCategory[];multiple?:boolean}){
 const input=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false),[stage,setStage]=useState(''),[error,setError]=useState('');
 const submit=async(files:File[],source:'manual'|'camera')=>{if(!files.length)return;setBusy(true);setError('');setStage('Subiendo archivos…');try{const documents=source==='camera'?[await imageFilesToPdf(files)]:files;await startDocumentImport(documents,kind,{source},(current,total)=>setStage(`Subiendo archivos: ${current}/${total}`));setStage('Importación registrada. Continúa en segundo plano.')}catch(e){setError((e as Error).message)}finally{setBusy(false);if(input.current)input.current.value='';if(camera.current)camera.current.value=''}};
 if(!open)return null;
 return <FormModal title={importLabel[kind]} subtitle="Puedes cerrar la ventana una vez registrada la importación. Las revisiones se conservan." onClose={onClose}><div className="uploadChoices"><button className="uploadChoice" disabled={busy} onClick={()=>input.current?.click()}><FileUp/>Subir documentos</button><button className="uploadChoice" disabled={busy} onClick={()=>camera.current?.click()}><Camera/>Escanear con cámara</button></div><input hidden ref={input} type="file" accept="application/pdf,image/*" multiple={multiple} onChange={e=>void submit(Array.from(e.target.files||[]),'manual')}/><input hidden ref={camera} type="file" accept="image/*" capture="environment" multiple onChange={e=>void submit(Array.from(e.target.files||[]),'camera')}/>{stage&&<p role="status">{busy&&<LoaderCircle className="spin" size={16}/>} {stage}</p>}{error&&<p className="errorBox" role="alert">{error}</p>}<ImportJobHistory kinds={[kind]} categories={categories}/></FormModal>;
}
