import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
const owner='00000000-0000-4000-8000-000000000001',source='00000000-0000-4000-8000-000000000002';
const document=()=>({supplier:{name:'Prueba SL',taxId:'B12345674',countryCode:'ES',email:'new@test.es'},type:'complete',number:'F-001',issueDate:'2026-09-20',currency:'EUR',lines:[{description:'Artículo',reference:'A-1',quantity:2,unitPrice:50,net:100,vatRate:21,vat:21,total:121,kind:'product'}],taxes:[{rate:21,base:100,amount:21}],subtotal:100,vat:21,surcharge:0,withholding:0,total:121,confidence:{supplier:.99,email:.99,taxId:.99,number:.99,issueDate:.99,currency:.99,lines:.99,taxes:.99,total:.99},pages:[1]});
async function database(){const db=new PGlite();await db.exec(`create schema auth;create schema private;create role anon;create role service_role;create role authenticated;create table auth.users(id uuid primary key);create table public.workspaces(id uuid primary key);insert into auth.users values('${owner}');insert into public.workspaces values('${owner}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;create function private.app_workspace_owner_id() returns uuid language sql stable as $$select auth.uid()$$;create function private.app_has_permission(text) returns boolean language sql stable as $$select coalesce(current_setting('test.permission',true),'true')='true'$$;set test.actor='${owner}';`);
let baseline=await readFile(new URL('../supabase/migrations/001_initial_schema.sql',import.meta.url),'utf8');baseline=baseline.replace(/create extension if not exists pgcrypto;/i,'');await db.exec(baseline.split('insert into storage.buckets')[0]);await db.exec(await readFile(new URL('../supabase/migrations/20260912134500_sync_product_supplier_with_invoices.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20260916092000_recalculate_product_price_history.sql',import.meta.url),'utf8'));
await db.exec(`alter table suppliers add column address text;alter table suppliers add column website text;alter table invoices add column equivalence_surcharge_amount numeric default 0;create table source_documents(id uuid primary key,owner_id uuid default auth.uid(),storage_path text,original_name text,mime_type text,file_hash text);alter table invoices add column source_document_id uuid references source_documents(id);insert into source_documents values('${source}','${owner}','${owner}/source/test.pdf','test.pdf','application/pdf','hash');grant usage on schema public,private,auth to authenticated;grant select,insert,update on all tables in schema public to authenticated;`);
await db.exec(`create table public.app_settings(owner_id uuid,config jsonb);create table public.automation_rules(owner_id uuid,rule_key text,enabled boolean,config jsonb);create table public.entity_alias_rules(owner_id uuid,entity_type text,alias text,target_entity_id uuid,active boolean,priority int);create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(bucket_id text,name text);create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;create function private.app_storage_folder_in_workspace(text) returns boolean language sql as $$select $1=auth.uid()::text$$;`);await db.exec('grant select on public.app_settings,public.automation_rules,public.entity_alias_rules to authenticated');await db.exec(await readFile(new URL('../supabase/migrations/20261002170000_invoice_engine.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20261002190000_invoice_engine.sql',import.meta.url),'utf8'));return db;}
async function stage(db,d){return (await db.query("select invoice_engine_stage($1,'page-1',$2,'ready','manual') id",[source,JSON.stringify(d)])).rows[0].id;}
test('migración y RPC guardan factura, proveedor, producto y líneas atómicamente',async()=>{const db=await database();const d=document(),id=await stage(db,d);const r=await db.query('select invoice_engine_commit($1,$2,false) result',[id,JSON.stringify(d)]);assert.ok(r.rows[0].result.invoiceId);assert.equal((await db.query('select count(*)::int n from invoice_lines')).rows[0].n,1);assert.equal((await db.query('select last_cost::float n from products')).rows[0].n,50);await db.close()});
test('fallo en línea revierte todo sin proveedores huérfanos',async()=>{const db=await database();const d=document();d.lines[0].net=90;const id=await stage(db,d);await assert.rejects(db.query('select invoice_engine_commit($1,$2,true)',[id,JSON.stringify(d)]));assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from suppliers')).rows[0].n,0);await db.close()});
test('reimportación idempotente no duplica costes ni facturas',async()=>{const db=await database();const d=document(),id=await stage(db,d);await db.query('select invoice_engine_commit($1,$2,false)',[id,JSON.stringify(d)]);await db.query('select invoice_engine_commit($1,$2,false)',[id,JSON.stringify(d)]);assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,1);await db.close()});
test('sin permiso y otro tenant no pueden leer ni confirmar trabajos',async()=>{const db=await database();const id=await stage(db,document());await db.exec("set role authenticated;set test.permission='false'");assert.equal((await db.query('select * from invoice_engine_jobs')).rows.length,0);await assert.rejects(db.query('select invoice_engine_commit($1,$2,true)',[id,JSON.stringify(document())]));await db.close()});
test('corrección revisada se aprende sin sobreescribir contacto existente',async()=>{const db=await database();await db.exec(`insert into suppliers(name,tax_id,email) values('Prueba SL','B12345674','keep@test.es')`);const d=document(),id=await stage(db,d);d.supplier.phone='123456789';await db.query('select invoice_engine_commit($1,$2,true)',[id,JSON.stringify(d)]);assert.equal((await db.query('select email from suppliers')).rows[0].email,'keep@test.es');assert.equal((await db.query('select count(*)::int n from invoice_engine_corrections')).rows[0].n,1);await db.close()});
test('series distintas no se fusionan aunque número fecha y total coincidan',async()=>{const db=await database();for(const [i,series] of ['A','B'].entries()){const d={...document(),number:'001',series};const id=(await db.query("select invoice_engine_stage($1,$2,$3,'ready','manual') id",[source,`series-${i}`,JSON.stringify(d)])).rows[0].id;await db.query('select invoice_engine_commit($1,$2,false)',[id,JSON.stringify(d)]);}assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,2);await db.close()});
test('mismo número en distinta moneda se manda a revisión en vez de declarar duplicado',async()=>{const db=await database();const d=document(),id=await stage(db,d);await db.query('select invoice_engine_commit($1,$2,false)',[id,JSON.stringify(d)]);d.currency='USD';const other=(await db.query("select invoice_engine_stage($1,'currency',$2,'ready','manual') id",[source,JSON.stringify(d)])).rows[0].id;await assert.rejects(db.query('select invoice_engine_commit($1,$2,false)',[other,JSON.stringify(d)]),/distinta fecha o total/);await db.close()});
test('misma descripción con referencias distintas crea productos separados',async()=>{const db=await database();for(const [i,reference] of ['A-1','A-2'].entries()){const d=document();d.number=`F-${i}`;d.lines[0].reference=reference;const id=(await db.query("select invoice_engine_stage($1,$2,$3,'ready','manual') id",[source,`sku-${i}`,JSON.stringify(d)])).rows[0].id;await db.query('select invoice_engine_commit($1,$2,false)',[id,JSON.stringify(d)]);}assert.equal((await db.query('select count(*)::int n from products')).rows[0].n,2);await db.close()});
test('revisión resuelve advertencia de segmentación de manera explícita',async()=>{const db=await database();const d=document();d.segmentationWarning='Revisar páginas';const id=await stage(db,d);await assert.rejects(db.query('select invoice_engine_commit($1,$2,true)',[id,JSON.stringify(d)]),/confirma la separación/);d.segmentationResolved=true;await db.query('select invoice_engine_commit($1,$2,true)',[id,JSON.stringify(d)]);assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,1);await db.close()});
test('otro workspace no puede leer ni confirmar un trabajo existente',async()=>{const db=await database();const id=await stage(db,document());await db.exec("set role authenticated;set test.actor='00000000-0000-4000-8000-000000000099';set test.permission='true'");assert.equal((await db.query('select * from invoice_engine_jobs')).rows.length,0);await assert.rejects(db.query('select invoice_engine_commit($1,$2,true)',[id,JSON.stringify(document())]),/ajena o inexistente/);await db.close()});
