import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import ts from 'typescript';
const compile=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const dataUrl=source=>`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;
const core=dataUrl(compile(await readFile(new URL('../supabase/functions/_shared/shipmentTracking.ts',import.meta.url),'utf8')));
const endpoint=compile(await readFile(new URL('../supabase/functions/order-logistics-state/index.ts',import.meta.url),'utf8'))
 .replace(/import \{ createClient \} from [^;]+;/,'const createClient=()=>globalThis.__trackingTestAdmin;')
 .replace("'../_shared/shipmentTracking.ts'",JSON.stringify(core));
const order={id:'order-1',owner_id:'tenant-a',tracking_number:'000123',tracking_url:'https://tracking.sendcloud.sc/forward?code=000123',raw_payload:{items:['preserved']},last_synced_at:'2026-10-02',shipping_provider:'sendcloud'};
async function run({row=order,account=null,request=async()=>new Response(null,{status:302,headers:{location:'https://future-carrier.example/result/000123'}})}={}){
 const calls=[],updates=[];
 const admin={auth:{getUser:async()=>({data:{user:{id:'user-1'}}})},rpc:async()=>({data:'{"token":"test-token"}'}),from(table){const filters=[];const q={select(){return q},eq(key,value){filters.push([key,value]);calls.push([table,key,value]);return q},neq(){return q},order(){return q},limit(){return q},update(value){updates.push(value);return q},async maybeSingle(){return {data:table==='app_users'?{active:true,role:'admin',data_owner_id:'tenant-a'}:table==='fulfillment_orders'?row:account,error:null}}};return q}};
 const previous={Deno:globalThis.Deno,fetch:globalThis.fetch};let handler;
 globalThis.__trackingTestAdmin=admin;globalThis.Deno={env:{get:key=>key==='SUPABASE_URL'?'https://supabase.example':key==='SUPABASE_SERVICE_ROLE_KEY'?'test-key':undefined},serve:value=>{handler=value}};globalThis.fetch=request;
 try{await import(dataUrl(endpoint+`\n// test ${Math.random()}`));const response=await handler(new Request('https://function.example/',{method:'POST',headers:{Authorization:'Bearer token','Content-Type':'application/json'},body:JSON.stringify({action:'resolve_tracking_link',orderId:'order-1'})}));return {status:response.status,body:await response.json(),calls,updates}}finally{globalThis.Deno=previous.Deno;globalThis.fetch=previous.fetch;delete globalThis.__trackingTestAdmin}
}
test('tracking endpoint scopes order lookup and cache write to the authenticated tenant',async()=>{const result=await run();assert.equal(result.status,200);assert.equal(result.body.url,'https://future-carrier.example/result/000123');assert.ok(result.calls.filter(call=>call[0]==='fulfillment_orders'&&call[1]==='owner_id').every(call=>call[2]==='tenant-a'));assert.deepEqual(result.updates[0].raw_payload.items,['preserved']);assert.equal(result.updates[0].raw_payload._zenvia_tracking.number,'000123');assert.ok(result.calls.some(call=>call[1]==='last_synced_at'&&call[2]===order.last_synced_at))});
test('an order unavailable to the tenant is never resolved',async()=>{let fetched=false;const result=await run({row:null,request:async()=>{fetched=true;throw Error('unexpected fetch')}});assert.equal(result.status,404);assert.equal(fetched,false)});
test('a new Envia carrier works from shipment metadata with the owning account',async()=>{const calls=[];const result=await run({row:{...order,tracking_url:null,shipping_provider:'envia',shipping_integration_account_id:'account-a'},account:{id:'account-a',secret_id:'secret-a',config:{environment:'production'}},request:async(url,init)=>{calls.push([url,init.headers.Authorization]);return Response.json({data:[{carrier:'new-carrier',carrierTrackingUrl:'https://new-carrier.example/shipment/000123'}]})}});assert.equal(result.body.url,'https://new-carrier.example/shipment/000123');assert.deepEqual(calls,[['https://queries.envia.com/guide/000123','Bearer test-token']]);assert.ok(result.calls.some(call=>call[0]==='integration_accounts'&&call[1]==='owner_id'&&call[2]==='tenant-a'));assert.ok(result.calls.some(call=>call[0]==='integration_accounts'&&call[1]==='id'&&call[2]==='account-a'))});
test('missing carrier link produces an explicit unavailable result without guessing',async()=>{const result=await run({row:{...order,tracking_url:null,shipping_provider:'other'}});assert.equal(result.body.status,'unavailable');assert.equal(result.body.url,null);assert.match(result.body.message,/enlace de seguimiento/);assert.equal(result.updates.length,0)});
