import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
function fixture({timeout=false,denied=false,internal=false}={}){
 let handler,op=null,mutations=0,cancelled=false;const order={id:'order',owner_id:'owner',source_channel:'shopify',source_integration_account_id:'account',order_id:'gid://shopify/Order/1'};
 const admin={from(table){const q={select(){return q},eq(){return q},in(){return q},async maybeSingle(){return {data:order}},then(resolve,reject){return Promise.resolve({data:op?[op]:[]}).then(resolve,reject)}};return q},async rpc(name,p){if(name==='integration_start_cancellation'){if(op)return {data:{claimed:false,operation:{...op}}};op={id:'op',created_at:new Date().toISOString(),kind:p.p_kind,status:'submitting',details:p.p_details};return {data:{claimed:true,operation:{...op}}}}if(name==='integration_finish_cancellation'){op={...op,status:p.p_status,message:p.p_message,remote_id:p.p_remote_id};return {data:null}}throw new Error(name)}};
 class CancellationRejected extends Error{}
 const globals={Error,Response,Request,AbortSignal,Date,console,CancellationRejected,createAdminClient:()=>admin,authenticateUser:async()=>({data_owner_id:'owner',user_id:'user',role:denied?'viewer':'admin',permissions:[]}),cancellationAccount:async()=>({account:{id:'account'}}),shopifyAccountCredentials:async()=>({shopDomain:'example.myshopify.com',apiVersion:'2026-07',accessToken:'fixture'}),shopifyStoredApplicationCredentials:async()=>({}),fetch:async(_url,request)=>{const b=JSON.parse(request.body);if(b.query.startsWith('mutation')){mutations++;if(timeout)throw new Error('timeout');if(internal)return Response.json({errors:[{message:'Internal error',extensions:{code:'INTERNAL_SERVER_ERROR'}}]});return Response.json({data:{orderCancel:{job:{id:'job'},orderCancelUserErrors:[],userErrors:[]}}})}if(b.query.includes('job('))return Response.json({data:{job:{done:false}}});return Response.json({data:{order:{id:order.order_id,cancelledAt:cancelled?'today':null}}})},Deno:{serve:fn=>handler=fn}};
 const helper=stripTypeScriptTypes(fs.readFileSync('supabase/functions/_shared/orderCancellation.ts','utf8').replaceAll('export ',''));const source=stripTypeScriptTypes(fs.readFileSync('supabase/functions/order-cancellation/index.ts','utf8').replace(/^import .*\n/gm,''));vm.runInNewContext(helper+'\n'+source,globals);
 const invoke=async(action='cancel')=>{const res=await handler(new Request('https://fixture',{method:'POST',body:JSON.stringify({action,orderId:'order',kind:'order',reason:'customer'})}));return {status:res.status,data:await res.json()}};
 return {invoke,get mutations(){return mutations},set cancelled(v){cancelled=v},get op(){return op}};
}
test('Shopify cancellation stores pending, retries do not send again, and only remote cancelledAt confirms',async()=>{const f=fixture();let result=await f.invoke();assert.equal(result.data.operations[0].status,'pending');await f.invoke();assert.equal(f.mutations,1);await f.invoke('refresh');assert.equal(f.op.status,'pending');f.cancelled=true;result=await f.invoke('refresh');assert.equal(result.data.operations[0].status,'confirmed');assert.equal(f.mutations,1)});
test('a lost Shopify mutation response remains unknown and never automatically repeats the mutation',async()=>{const f=fixture({timeout:true});await f.invoke();assert.equal(f.op.status,'unknown');await f.invoke();await f.invoke('refresh');assert.equal(f.mutations,1);assert.notEqual(f.op.status,'confirmed')});
test('a caller without orders permission cannot issue cancellation',async()=>{const f=fixture({denied:true});const result=await f.invoke();assert.equal(result.status,403);assert.equal(f.mutations,0);assert.equal(f.op,null)});

test('HTTP 200 GraphQL internal errors remain unknown and cannot replay the cancellation mutation',async()=>{const f=fixture({internal:true});await f.invoke();assert.equal(f.op.status,'unknown');await f.invoke();assert.equal(f.mutations,1)});
