import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { ZENVIA_LOGO } from './branding';
import { AutoPagination } from './components/AutoPagination';
import { OrderLabelDefaults } from './components/OrderLabelDefaults';
import { PendingOrdersKpiHighlight } from './components/PendingOrdersKpiHighlight';
import { UnifiedListExperience } from './components/UnifiedListExperience';
import { ActionDialogHost } from './components/ActionDialogHost';
import { ActivityCenter } from './components/ActivityCenter';
import { AppErrorBoundary } from './components/AppErrorBoundary';
import { SettingsProvider } from './context/SettingsContext';
import './styles.css';
import './enhancements.css';
import './sidebar-brand.css';
import './gmail.css';
import './gmail-filter.css';
import './mobile-nav.css';
import './gmail-mobile.css';
import './gmail-preview.css';
import './history-theme.css';
import './mobile-session.css';
import './toast.css';
import './validation.css';
import './pagination.css';
import './readability.css';
import './modal-sticky-fix.css';
import './sales-config.css';
import './master-data.css';
import './supplier-period.css';
import './orders.css';
import './orders-status.css';
import './orders-edit.css';
import './orders-products.css';
import './orders-tracking.css';
import './orders-tracking-filter.css';
import './orders-label-default.css';
import './dashboard-summary.css';
import './amazon.css';
import './amazon-mapping.css';
import './interface-normalization.css';
import './modern-forms.css';
import './destructive-actions.css';
import './mobile-ui-normalization.css';
import './passkey.css';
import './unified-list-experience.css';
import './truncated-tooltip.css';
import './bulk-invoice-import.css';
import './dark-mode-consistency.css';
import './layout-polish.css';
import './action-dialog.css';
import './activity.css';
import './settings.css';
import './alerts.css';
import './app-agent.css';
import './theme-consistency.css';
import './responsive-hardening.css';

const favicon=document.querySelector<HTMLLinkElement>("link[rel~='icon']")||document.createElement('link');
favicon.rel='icon';
favicon.type='image/webp';
favicon.href=ZENVIA_LOGO;
if(!favicon.parentNode)document.head.appendChild(favicon);

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AppErrorBoundary><SettingsProvider><App/><ActionDialogHost/><ActivityCenter/><AutoPagination/><OrderLabelDefaults/><PendingOrdersKpiHighlight/><UnifiedListExperience/></SettingsProvider></AppErrorBoundary></React.StrictMode>);
