create table if not exists public.agent_tool_registry (
id uuid primary key default gen_random_uuid(),app text not null,tool_key text not null,domain text not null,display_name text not null,description text not null,permission text,action_type text not null check(action_type in('read','write','destructive')),requires_confirmation boolean not null default false,destructive boolean not null default false,handler text not null,enabled boolean not null default true,args_schema jsonb not null default '{}'::jsonb,result_contract text,updated_at timestamptz not null default now(),unique(app,tool_key));
create index if not exists agent_tool_registry_app_domain_idx on public.agent_tool_registry(app,domain,enabled);
revoke all on public.agent_tool_registry from public,anon,authenticated;
grant select on public.agent_tool_registry to service_role;

insert into public.agent_tool_registry(app,tool_key,domain,display_name,description,permission,action_type,requires_confirmation,destructive,handler,args_schema,result_contract) values
('gestion','dashboard.read','general','Consultar resumen','Lee KPIs, pendientes y alertas del workspace.','dashboard','read',false,false,'server:business_context','{}','Datos del workspace actual.'),
('gestion','orders.read','orders_shipping','Consultar pedidos','Busca pedidos, estados, etiquetas y tracking.','orders','read',false,false,'server:business_context','{}','Pedidos autorizados.'),
('gestion','orders.sync','orders_shipping','Sincronizar pedidos','Sincroniza pedidos con las integraciones configuradas.','orders','write',true,false,'client:sync_orders','{}','Número de pedidos sincronizados.'),
('gestion','expenses.read','expenses','Consultar gastos','Consulta facturas de gasto, estados y pagos.','invoices','read',false,false,'server:business_context','{}','Facturas de gasto autorizadas.'),
('gestion','expenses.open_import','expenses','Abrir importador','Abre el importador de facturas de gasto.','invoices','read',false,false,'client:open_expense_upload','{}','Abre el flujo sin persistir.'),
('gestion','expenses.set_status','expenses','Cambiar estado de gasto','Cambia estado contable de una factura de gasto.','invoices','write',true,false,'client:set_expense_status','{"type":"object","required":["invoiceId","status"]}','Estado actualizado.'),
('gestion','sales.read','sales_clients','Consultar facturación','Consulta facturas emitidas, vencimientos y cobros.','sales','read',false,false,'server:business_context','{}','Datos de facturación autorizados.'),
('gestion','clients.read','sales_clients','Consultar clientes','Busca clientes.','clients','read',false,false,'server:business_context','{}','Clientes autorizados.'),
('gestion','clients.create','sales_clients','Crear cliente','Crea un cliente.','clients','write',true,false,'client:create_client','{"type":"object","required":["name"]}','Cliente creado.'),
('gestion','products.read','catalog_suppliers','Consultar productos','Busca catálogo, SKU, EAN, costes y precios.','products','read',false,false,'server:business_context','{}','Productos autorizados.'),
('gestion','products.create','catalog_suppliers','Crear producto','Crea un producto.','products','write',true,false,'client:create_product','{"type":"object","required":["name"]}','Producto creado.'),
('gestion','suppliers.read','catalog_suppliers','Consultar proveedores','Busca proveedores e identidad fiscal.','suppliers','read',false,false,'server:business_context','{}','Proveedores autorizados.'),
('gestion','suppliers.create','catalog_suppliers','Crear proveedor','Crea un proveedor.','suppliers','write',true,false,'client:create_supplier','{"type":"object","required":["name"]}','Proveedor creado.'),
('gestion','amazon.read','amazon','Consultar Amazon','Consulta analítica, ventas, unidades, reembolsos e inventario.','amazon','read',false,false,'server:amazon_context','{}','Métricas del periodo solicitado.'),
('gestion','support.read','support','Consultar soporte','Consulta tickets y estados.','support','read',false,false,'server:business_context','{}','Tickets autorizados.'),
('gestion','settings.read','settings_admin','Consultar configuración','Explica configuración e integraciones.','settings','read',false,false,'server:knowledge','{}','Configuración documentada.'),
('gestion','admin.read','settings_admin','Consultar administración','Consulta usuarios, permisos y auditoría.','admin','read',false,false,'server:business_context','{}','Información autorizada.')
on conflict(app,tool_key) do update set domain=excluded.domain,display_name=excluded.display_name,description=excluded.description,permission=excluded.permission,action_type=excluded.action_type,requires_confirmation=excluded.requires_confirmation,destructive=excluded.destructive,handler=excluded.handler,args_schema=excluded.args_schema,result_contract=excluded.result_contract,enabled=true,updated_at=now();

insert into public.agent_knowledge_chunks(app,domain,module,screen,route,entity,content,keywords,permissions,action_type,requires_confirmation,integrations,version,source_file)
select * from(values
('gestion','general','Resumen','Resumen','dashboard',null,'Resumen muestra KPIs, alertas, pendientes y accesos rápidos. Los filtros de periodo afectan a los indicadores compatibles y todo respeta permisos y workspace.',array['resumen','dashboard','kpi','pendientes'],array['dashboard'],'read',false,array[]::text[],'2','src/pages/Dashboard.tsx'),
('gestion','sales_clients','Facturación','Facturas emitidas','sales','sales_invoice','Facturación gestiona borradores, emisión, vencimientos, cobros, descarga y envío de facturas de venta. No debe confundirse con Facturas de gasto.',array['factura venta','facturas emitidas','vencimiento','cobro'],array['sales'],'write',true,array[]::text[],'2','src/pages/SalesInvoices.tsx'),
('gestion','sales_clients','Recibos','Recibos','sales','receipt','Recibos registra cobros, incluso sin vincular a una factura cuando el flujo lo permite.',array['recibos','cobros','pago'],array['sales'],'write',true,array[]::text[],'2','src/pages/SalesReceipts.tsx'),
('gestion','sales_clients','Clientes','Clientes','clients','client','Clientes mantiene nombre o razón social, NIF/VAT, contacto, dirección, país y valores comerciales. El agente no inventa datos fiscales ausentes.',array['clientes','cif','nif','vat'],array['clients'],'write',true,array[]::text[],'2','src/pages/Clients.tsx'),
('gestion','orders_shipping','Pedidos','Listado de pedidos','orders','fulfillment_order','Pedidos es la fuente operativa del pedido. El origen puede ser Amazon, Shopify u otro canal y el proveedor logístico se elige después.',array['pedidos','amazon','shopify','cliente'],array['orders'],'read',false,array['amazon','shopify'],'2','src/pages/Orders.tsx'),
('gestion','orders_shipping','Pedidos','Edición de pedido','orders','fulfillment_order','Antes de crear etiqueta se pueden corregir destinatario, teléfono, dirección, peso y medidas. Los cambios se guardan en ZENVIA y solo se envían al proveedor elegido cuando corresponde.',array['editar pedido','dirección','peso','medidas'],array['orders'],'write',true,array['mrw','envia','sendcloud'],'2','src/components/OrderEditModal.tsx'),
('gestion','orders_shipping','Envíos','Comparador','orders','shipping_option','ZENVIA compara opciones logísticas habilitadas y ordena por precio cuando existe. Las reglas pueden elegir proveedor, cuenta, transportista y servicio.',array['comparar envíos','tarifa','reglas','transportista'],array['orders'],'read',false,array['mrw','envia','sendcloud'],'2','src/pages/Orders.tsx'),
('gestion','orders_shipping','Envíos','Etiquetados','orders','fulfillment_order','Etiquetados contiene pedidos con etiqueta creada que aún no han progresado según tracking reconocido. Enviados contiene progreso logístico y Cancelados se separa cuando corresponde.',array['etiquetados','enviados','cancelados','tracking'],array['orders'],'read',false,array['mrw','envia','sendcloud'],'2','src/pages/Orders.tsx'),
('gestion','orders_shipping','Envíos','Impresión de etiquetas','orders','shipping_label','La impresión admite formatos configurados. El estado de impresión se registra cuando ZENVIA conoce el evento; etiquetas creadas fuera pueden tener historial desconocido.',array['imprimir etiqueta','a6','a4','impresa'],array['orders'],'write',false,array['mrw','envia','sendcloud'],'2','src/pages/Orders.tsx'),
('gestion','expenses','Gastos','Facturas de gasto','invoices','invoice','Facturas de gasto son facturas recibidas. Estados contables y de pago son independientes; se pueden filtrar, ordenar, revisar, contabilizar, pagar y exportar según permisos.',array['factura gasto','pendiente','revisada','contabilizada','pagada'],array['invoices'],'write',true,array['gmail'],'2','src/pages/Invoices.tsx'),
('gestion','expenses','Gastos','Añadir factura','invoices','invoice_import','Añadir factura procesa un documento individual. Importar facturas procesa varios. Ambos comparten el mismo motor de lectura y validación.',array['añadir factura','importar factura','ocr','pdf'],array['invoices'],'write',true,array[]::text[],'2','src/components/UploadInvoiceModal.tsx'),
('gestion','expenses','Gastos','Importación masiva','invoices','invoice_import','La importación masiva procesa varios PDFs, detecta duplicados y presenta candidatos para revisión antes de guardar.',array['importación masiva','duplicado','varias facturas'],array['invoices'],'write',true,array[]::text[],'2','src/components/BulkInvoiceImportModal.tsx'),
('gestion','expenses','Gastos','Gmail','invoices','gmail_import','Gmail usa el mismo pipeline de facturas de gasto. Si falta fecha, número, proveedor o cierre fiscal fiable debe pedir revisión y no inventar.',array['gmail','fecha factura','iva','adjunto'],array['invoices'],'write',true,array['gmail'],'2','src/pages/Gmail.tsx'),
('gestion','expenses','Gastos','Motor fiscal','invoices','invoice_import','El motor reconcilia base, IVA, recargo, retención y total con evidencia y aritmética. IVA cero exige evidencia de exención o reverse charge.',array['iva','base imponible','recargo','retención','reverse charge'],array['invoices'],'read',false,array[]::text[],'2','src/services/invoiceImportPipeline.ts'),
('gestion','catalog_suppliers','Productos','Productos','products','product','Productos mantiene nombre, SKU, EAN, unidad, categoría, coste, precio, IVA y proveedor.',array['producto','sku','ean','coste','precio'],array['products'],'write',true,array['amazon'],'2','src/pages/Products.tsx'),
('gestion','catalog_suppliers','Proveedores','Proveedores','suppliers','supplier','Proveedores mantiene identidad fiscal, contacto, dirección, web, tipo y categoría habitual; se normalizan identidades para evitar duplicados.',array['proveedor','cif','web','tipo proveedor'],array['suppliers'],'write',true,array[]::text[],'2','src/pages/Suppliers.tsx'),
('gestion','amazon','Amazon','Resumen','amazon','amazon_analytics','Amazon Analytics usa filtros de periodo y marketplace y muestra ventas, unidades, reembolsos y rentabilidad con datos sincronizados.',array['amazon analytics','ventas','unidades','reembolsos','rentabilidad'],array['amazon'],'read',false,array['amazon'],'2','src/components/amazon/AmazonSummary.tsx'),
('gestion','amazon','Amazon','Productos Amazon','amazon','amazon_product','Productos Amazon muestra ASIN/SKU, imagen, nombre Amazon, nombre interno y vinculaciones. Los no vinculados se identifican aparte.',array['asin','sku amazon','vincular','sin vincular'],array['amazon'],'write',true,array['amazon'],'2','src/components/amazon/AmazonProducts.tsx'),
('gestion','support','Soporte','Tickets','support','support_ticket','Soporte permite crear tickets, adjuntar archivos y seguir conversación y estado. Las acciones administrativas dependen de permisos y auditoría.',array['ticket','soporte','adjunto','respuesta'],array['support'],'write',true,array[]::text[],'2','src/pages/Support.tsx'),
('gestion','settings_admin','Configuración','Integraciones','settings','integration_account','Integraciones admite varias cuentas por proveedor. Amazon y Shopify son canales de venta; MRW, Envia.com y Sendcloud son proveedores logísticos o plataformas de envío; Gmail importa documentos.',array['integraciones','amazon','shopify','mrw','envia','gmail'],array['settings'],'write',true,array['amazon','shopify','mrw','envia','sendcloud','gmail'],'2','src/pages/Settings.tsx'),
('gestion','settings_admin','Administración','Usuarios y permisos','admin','app_user','Administración gestiona usuarios, roles, permisos y auditoría. El agente no puede elevar permisos ni cruzar workspaces.',array['administración','usuarios','permisos','auditoría'],array['admin'],'write',true,array[]::text[],'2','src/pages/Admin.tsx')
) as v(app,domain,module,screen,route,entity,content,keywords,permissions,action_type,requires_confirmation,integrations,version,source_file)
where not exists(select 1 from public.agent_knowledge_chunks k where k.app=v.app and k.module=v.module and coalesce(k.screen,'')=coalesce(v.screen,'') and k.version=v.version);