insert into public.agent_knowledge_chunks(app,domain,module,screen,route,entity,content,keywords,permissions,action_type,requires_confirmation,integrations,version,source_file)
select * from(values
('gestion','expenses','Gastos','Centro de gastos','invoices','invoice','El centro de Gastos separa Facturas de gasto e Importar desde Gmail. La primera gestiona documentos ya incorporados y altas manuales o masivas; Gmail descubre adjuntos y los pasa por el mismo motor común.',array['centro gastos','gmail','facturas gasto'],array['invoices'],'read',false,array['gmail'],'3','src/pages/ExpenseInvoicesHub.tsx'),
('gestion','expenses','Gastos','Detalle de factura','invoices','invoice','El detalle de una factura de gasto muestra proveedor, número, fecha, base, IVA, recargo, retención, total, estado, pago, líneas y documento cuando existe. Los cambios de estado o proveedor deben usar la factura identificada.',array['detalle factura','base','iva','retención','estado pago'],array['invoices'],'write',true,array[]::text[],'3','src/components/InvoiceDetailModal.tsx'),
('gestion','catalog_suppliers','Productos','Editor de producto','products','product','El editor de producto permite nombre, SKU, EAN, categoría, unidad, coste, precio de venta, IVA y proveedor según configuración. No se deben inventar SKU, EAN ni costes ausentes.',array['editar producto','sku','ean','coste','precio venta','iva'],array['products'],'write',true,array[]::text[],'3','src/components/ProductModal.tsx'),
('gestion','catalog_suppliers','Proveedores','Editor de proveedor','suppliers','supplier','El editor de proveedor permite identidad fiscal, contacto, dirección, web, tipo de proveedor y categoría habitual. Tipo de proveedor no es lo mismo que categoría de gasto.',array['editar proveedor','tipo proveedor','categoría habitual','cif'],array['suppliers'],'write',true,array[]::text[],'3','src/components/SupplierModal.tsx'),
('gestion','amazon','Amazon','Filtros Amazon','amazon','amazon_filter','Los filtros de Amazon incluyen periodo y marketplaces. Por defecto puede usarse el mes actual y Todos los marketplaces según preferencias. Las cifras deben respetar siempre los filtros activos.',array['filtros amazon','mes actual','marketplaces','periodo'],array['amazon'],'read',false,array['amazon'],'3','src/components/amazon/AmazonFilters.tsx'),
('gestion','amazon','Amazon','Inventario','amazon','amazon_inventory','Inventario muestra stock sincronizado por producto o marketplace cuando existe evidencia. Si la sincronización está incompleta el agente debe indicarlo en vez de inferir existencias.',array['inventario','stock','fba','fbm'],array['amazon'],'read',false,array['amazon'],'3','src/components/amazon/AmazonInventory.tsx'),
('gestion','amazon','Amazon','Sin vincular','amazon','amazon_mapping','Sin vincular muestra referencias Amazon que todavía no están asociadas a productos internos. El flujo de vinculación permite elegir productos internos y puede incluir más de un componente cuando el modelo de coste lo requiere.',array['sin vincular','vincular','asin','producto interno'],array['amazon'],'write',true,array['amazon'],'3','src/components/amazon/AmazonUnmapped.tsx'),
('gestion','settings_admin','Configuración','General','settings','settings','General contiene identidad de empresa, moneda, zona horaria, idioma, formato de fecha, página inicial y branding corporativo disponible.',array['configuración general','moneda','zona horaria','idioma','logo'],array['settings'],'write',true,array[]::text[],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Configuración','Plan y facturación','settings','subscription','Plan y facturación muestra plan, consumo, límites, caducidad, facturas de suscripción y opciones de cobro disponibles para el cliente.',array['plan','facturación suscripción','caducidad','paypal'],array['settings'],'read',false,array['paypal'],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Configuración','Gastos e importación','settings','expense_settings','Gastos e importación controla revisión, duplicados, Gmail, límites de adjuntos, categoría por defecto y reglas del motor de facturas recibidas.',array['configuración gastos','duplicados','gmail','revisión'],array['settings'],'write',true,array['gmail'],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Configuración','Pedidos','settings','order_settings','Pedidos contiene preferencias generales de pedidos, país de origen, comportamiento de etiquetas y valores predeterminados no específicos de un cliente salvo que el propio cliente los configure.',array['configuración pedidos','origen','etiquetas','defaults'],array['settings'],'write',true,array[]::text[],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Configuración','Envíos','settings','shipping_settings','Envíos controla modo de selección, número de opciones destacadas, reglas de selección, formatos de etiqueta y parámetros logísticos. No debe imponer preferencias hardcodeadas de ZENVIA COMMERCE.',array['configuración envíos','reglas','más barato','a6','a4'],array['settings'],'write',true,array['mrw','envia','sendcloud'],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Configuración','Integraciones','settings','integration_account','Integraciones permite múltiples cuentas. Cada conexión debe conservar su configuración y credenciales separadas. Las notificaciones de error deben aparecer por encima de modales y usar el estilo global.',array['integraciones','cuentas','credenciales','probar conexión'],array['settings'],'write',true,array['amazon','shopify','mrw','envia','sendcloud','gmail'],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Configuración','Alertas y automatizaciones','settings','automation_rule','Alertas y automatizaciones define avisos de negocio y acciones controladas. Las automatizaciones no deben ejecutar operaciones destructivas sin confirmación o permiso explícito.',array['alertas','automatizaciones','notificaciones'],array['settings'],'write',true,array[]::text[],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Configuración','Preferencias','settings','user_preferences','Mis preferencias contiene opciones de interfaz propias del usuario, como columnas, KPIs, filtros o presentación cuando estén disponibles. No deben alterar la configuración global de otros usuarios.',array['preferencias','columnas','kpi','filtros'],array['settings'],'write',false,array[]::text[],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Configuración','Mantenimiento','settings','maintenance','Mantenimiento contiene diagnósticos y reparaciones controladas como duplicados, reconstrucciones y exportación de configuración. Las reparaciones deben previsualizarse y respetar confirmación.',array['mantenimiento','duplicados','reconstrucción','exportar configuración'],array['settings'],'write',true,array[]::text[],'3','src/pages/Settings.tsx'),
('gestion','settings_admin','Administración','Usuarios','admin','app_user','Usuarios permite gestionar acceso al workspace, rol, permisos, invitaciones y acciones administrativas disponibles. Nunca se puede actuar sobre otro workspace.',array['usuarios','rol','permisos','invitar'],array['admin'],'write',true,array[]::text[],'3','src/pages/Admin.tsx'),
('gestion','settings_admin','Administración','Auditoría','admin','audit_entry','Auditoría registra cambios relevantes realizados por usuarios y procesos para mantener trazabilidad. Es información de lectura salvo operaciones específicas de mantenimiento.',array['auditoría','historial','cambios','trazabilidad'],array['admin'],'read',false,array[]::text[],'3','src/pages/Admin.tsx'),
('gestion','support','Soporte','Detalle de ticket','support','support_ticket','El detalle de ticket reúne asunto, mensajes, adjuntos, estado y actividad. Antes de responder, editar o eliminar el agente debe identificar de forma inequívoca el ticket y verificar permisos.',array['detalle ticket','responder ticket','eliminar ticket','adjuntos'],array['support'],'write',true,array[]::text[],'3','src/pages/Support.tsx')
) as v(app,domain,module,screen,route,entity,content,keywords,permissions,action_type,requires_confirmation,integrations,version,source_file)
where not exists(select 1 from public.agent_knowledge_chunks k where k.app=v.app and k.module=v.module and coalesce(k.screen,'')=coalesce(v.screen,'') and k.version=v.version);