-- Common contract used by both local agents. Only server code accesses catalogs.
alter table public.agent_knowledge_chunks enable row level security;
alter table public.agent_tool_registry enable row level security;
revoke all on public.agent_knowledge_chunks,public.agent_tool_registry from public,anon,authenticated;
grant select on public.agent_knowledge_chunks,public.agent_tool_registry to service_role;
alter function public.agent_knowledge_search(text,text,int) security invoker;
create or replace function public.agent_knowledge_search_authorized(p_app text,p_query text,p_permissions text[],p_limit int default 5)
returns table(id uuid,domain text,module text,screen text,route text,content text,permissions text[],action_type text,requires_confirmation boolean,integrations text[],rank real)
language sql stable security invoker set search_path=public,pg_catalog as $$
with q as (
select websearch_to_tsquery('spanish',trim(coalesce(p_query,''))) strict_query,
websearch_to_tsquery('spanish',regexp_replace(trim(coalesce(p_query,'')),'\s+',' OR ','g')) broad_query
), latest as (
select distinct on(k.module,coalesce(k.screen,'')) k.*
from public.agent_knowledge_chunks k where k.app=p_app and k.permissions <@ coalesce(p_permissions,'{}'::text[])
order by k.module,coalesce(k.screen,''),k.version desc,k.updated_at desc
),docs as (
select k.*,setweight(to_tsvector('spanish',coalesce(k.module,'')||' '||coalesce(k.screen,'')||' '||array_to_string(k.keywords,' ')),'A')||setweight(to_tsvector('spanish',k.content),'B') document from latest k
)
select d.id,d.domain,d.module,d.screen,d.route,d.content,d.permissions,d.action_type,d.requires_confirmation,d.integrations,
(ts_rank_cd(d.document,q.strict_query)*3+ts_rank_cd(d.document,q.broad_query))::real rank
from docs d,q where d.document@@q.strict_query or d.document@@q.broad_query
order by rank desc,d.updated_at desc limit greatest(1,least(coalesce(p_limit,5),10));
$$;
revoke all on function public.agent_knowledge_search_authorized(text,text,text[],int) from public,anon,authenticated;
grant execute on function public.agent_knowledge_search_authorized(text,text,text[],int) to service_role;
insert into public.agent_tool_registry(app,tool_key,domain,display_name,description,permission,action_type,requires_confirmation,destructive,handler,args_schema,result_contract) values
('gestion','expenses.set_payment','expenses','Cambiar pago de gasto','Cambia pago de una factura identificada.','invoices','write',true,false,'client:set_expense_payment','{}','Estado de pago actualizado.'),
('gestion','support.create','support','Crear ticket','Abre una incidencia con asunto y descripción.','support','write',true,false,'client:create_support_ticket','{}','Número de ticket creado.'),
('gestion','amazon.sync','amazon','Sincronizar Amazon','Solicita trabajos en las cuentas configuradas.','amazon','write',true,false,'client:sync_amazon','{}','Trabajos solicitados; no implica sincronización finalizada.'),
('gestion','settings.read','settings_admin','Consultar integraciones','Lee estado de cuentas sin credenciales.','settings','read',false,false,'server:business_context','{}','Cuentas visibles sin secretos.'),
('gestion','admin.read','settings_admin','Consultar administración','Lee usuarios y auditoría del workspace.','admin','read',false,false,'server:business_context','{}','Usuarios y movimientos autorizados.')
on conflict(app,tool_key) do update set enabled=true;
update public.agent_tool_registry set args_schema='{"type":"object","additionalProperties":false,"properties":{},"required":[]}'::jsonb where app='gestion' and action_type='read';
update public.agent_tool_registry set args_schema='{"type":"object","additionalProperties":false,"properties":{"name":{"type":"string","minLength":1,"maxLength":200},"taxId":{"type":"string","minLength":1,"maxLength":80},"email":{"type":"string","minLength":1,"maxLength":254,"pattern":"^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"},"phone":{"type":"string","minLength":1,"maxLength":80},"city":{"type":"string","minLength":1,"maxLength":120},"countryCode":{"type":"string","pattern":"^[A-Z]{2}$"},"unit":{"type":"string","minLength":1,"maxLength":40},"sku":{"type":"string","minLength":1,"maxLength":120},"ean":{"type":"string","minLength":1,"maxLength":80},"category":{"type":"string","minLength":1,"maxLength":100},"price":{"type":"number","minimum":0},"salePrice":{"type":"number","minimum":0},"salesTaxRate":{"type":"number","minimum":0,"maximum":100},"supplierType":{"type":"string","enum":["unclassified","goods","service","both"]},"invoiceId":{"type":"string","minLength":1,"maxLength":80},"status":{"type":"string","enum":["pending","reviewed","accounted"]},"paymentStatus":{"type":"string","enum":["paid","unpaid"]},"subject":{"type":"string","minLength":3,"maxLength":200},"description":{"type":"string","minLength":3,"maxLength":4000}},"required":["name"]}'::jsonb where app='gestion' and tool_key='clients.create';
update public.agent_tool_registry set args_schema='{"type":"object","additionalProperties":false,"properties":{"name":{"type":"string","minLength":1,"maxLength":200},"taxId":{"type":"string","minLength":1,"maxLength":80},"email":{"type":"string","minLength":1,"maxLength":254,"pattern":"^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"},"phone":{"type":"string","minLength":1,"maxLength":80},"city":{"type":"string","minLength":1,"maxLength":120},"countryCode":{"type":"string","pattern":"^[A-Z]{2}$"},"unit":{"type":"string","minLength":1,"maxLength":40},"sku":{"type":"string","minLength":1,"maxLength":120},"ean":{"type":"string","minLength":1,"maxLength":80},"category":{"type":"string","minLength":1,"maxLength":100},"price":{"type":"number","minimum":0},"salePrice":{"type":"number","minimum":0},"salesTaxRate":{"type":"number","minimum":0,"maximum":100},"supplierType":{"type":"string","enum":["unclassified","goods","service","both"]},"invoiceId":{"type":"string","minLength":1,"maxLength":80},"status":{"type":"string","enum":["pending","reviewed","accounted"]},"paymentStatus":{"type":"string","enum":["paid","unpaid"]},"subject":{"type":"string","minLength":3,"maxLength":200},"description":{"type":"string","minLength":3,"maxLength":4000}},"required":["name"]}'::jsonb where app='gestion' and tool_key='products.create';
update public.agent_tool_registry set args_schema='{"type":"object","additionalProperties":false,"properties":{"name":{"type":"string","minLength":1,"maxLength":200},"taxId":{"type":"string","minLength":1,"maxLength":80},"email":{"type":"string","minLength":1,"maxLength":254,"pattern":"^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"},"phone":{"type":"string","minLength":1,"maxLength":80},"city":{"type":"string","minLength":1,"maxLength":120},"countryCode":{"type":"string","pattern":"^[A-Z]{2}$"},"unit":{"type":"string","minLength":1,"maxLength":40},"sku":{"type":"string","minLength":1,"maxLength":120},"ean":{"type":"string","minLength":1,"maxLength":80},"category":{"type":"string","minLength":1,"maxLength":100},"price":{"type":"number","minimum":0},"salePrice":{"type":"number","minimum":0},"salesTaxRate":{"type":"number","minimum":0,"maximum":100},"supplierType":{"type":"string","enum":["unclassified","goods","service","both"]},"invoiceId":{"type":"string","minLength":1,"maxLength":80},"status":{"type":"string","enum":["pending","reviewed","accounted"]},"paymentStatus":{"type":"string","enum":["paid","unpaid"]},"subject":{"type":"string","minLength":3,"maxLength":200},"description":{"type":"string","minLength":3,"maxLength":4000}},"required":["name"]}'::jsonb where app='gestion' and tool_key='suppliers.create';
update public.agent_tool_registry set args_schema='{"type":"object","additionalProperties":false,"properties":{"invoiceId":{"type":"string","minLength":1,"maxLength":80},"status":{"type":"string","enum":["pending","reviewed","accounted"]}},"required":["invoiceId","status"]}'::jsonb where app='gestion' and tool_key='expenses.set_status';
update public.agent_tool_registry set args_schema='{"type":"object","additionalProperties":false,"properties":{"invoiceId":{"type":"string","minLength":1,"maxLength":80},"paymentStatus":{"type":"string","enum":["paid","unpaid"]}},"required":["invoiceId","paymentStatus"]}'::jsonb where app='gestion' and tool_key='expenses.set_payment';
update public.agent_tool_registry set args_schema='{"type":"object","additionalProperties":false,"properties":{"subject":{"type":"string","minLength":3,"maxLength":200},"description":{"type":"string","minLength":3,"maxLength":4000}},"required":["subject","description"]}'::jsonb where app='gestion' and tool_key='support.create';
update public.agent_tool_registry set requires_confirmation=true where app='gestion' and action_type in ('write','destructive');

